# BOT TELEGRAM
api.telegram.key=${TELEGRAMBOT_KEYTEST}
id.telegram.channel=${TELEGRAMCHAT_IDTEST}


# Habilitar o console H2
spring.h2.console.enabled=true
# Caminho do console
spring.h2.console.path=/h2-console
# Configurações do Banco
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
