# TELEGRAM
api.telegram.key=${TELEGRAMBOT_KEY}
id.telegram.channel=${TELEGRAMCHAT_ID}

# DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${UK_DB_URL}
spring.datasource.username=${UK_DB_USERNAME}
spring.datasource.password=${UK_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


