name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Para app, limpa JAR antigo e cria pasta
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            sudo systemctl stop unemployment-killer || true
            mkdir -p /opt/unemployment-killer
            rm -f /opt/unemployment-killer/*.jar

      - name: Copia o JAR para a VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "target/unemployment-killer-0.0.1-SNAPSHOT.jar"
          target: "/opt/unemployment-killer/unemployment-killer-0.0.1-SNAPSHOT.jar"

      - name: Sobe a aplicação e verifica
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            sudo systemctl start unemployment-killer
            sleep 15
            if sudo systemctl is-active --quiet unemployment-killer; then
              echo "Subiu pra vps"
            else
              echo "falha subir pra vps"
              sudo journalctl -u unemployment-killer --no-pager -n 50
              exit 1
            fi